version: '3.8'

networks:
  default:
    driver: bridge

services:

  mysql:
    image: mysql:latest
    container_name: freeGiftDB
    restart: always
    env_file:
      - .env
    environment:
      MYSQL_DATABASE: ${DATABASE}
      MYSQL_PASSWORD: ${PASSWORD}
      MYSQL_ROOT_PASSWORD: ${PASSWORD}
      MYSQL_USER: ${USER}
    ports:
      - "3305:3306"
    volumes:
      - mysql:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

  rabbitmq:
    image: rabbitmq:3-management-alpine
    environment:
      RABBITMQ_DEFAULT_PASS: ${PASSWORD}
      RABBITMQ_DEFAULT_USER: ${USER}
    ports:
      # AMQP protocol port
      - "5670:5672"
      # HTTP management UI
      - "15672:15672"
    volumes:
      - rabbitmqlib:/var/lib/rabbitmq/
      - rabbitmqlog:/var/log/rabbitmq

volumes:
  mysql:
  rabbitmqlib:
  rabbitmqlog: